Closes #50 Increase unit test coverage for derive_params_growth_height
pharmaverse/admiralpeds pull request #54
Opened 2024-06-23 19:58 UTC by ahasoplakus

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/CONTRIBUTING.html#detailed-development-process) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [ ] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` under the header `# admiralpeds (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiralpeds site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the Reference page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2024-06-24 08:39 UTC, rossfarrugia commented
@zdz2101 best for you to review this one please and double check against all David advised over email.

2024-06-26 16:14 UTC, Fanny-Gautier commented
Is there any test for outlier data ?

2024-06-27 07:31 UTC, rossfarrugia commented
> Is there any test for outlier data ?

@ahasoplakus

2024-06-28 19:48 UTC, zdz2101 requested changes
@ahasoplakus Thank you for all your help so far! Looks great, just needs a couple more examples, as cited above, is it possible to add outlier cases? Something like Z-scores of > |10| so both -10 and 10, with the currently pre-existing metadata, to make it easier you can generate fake data and use just one metadataset like the `who_wt_for_lgth_boys` to trim down the preprocessing work

2024-06-28 19:48 UTC, zdz2101 commented on tests/testthat/test-derive_params_growth_height.R
> +    ~USUBJID, ~SEX, ~HEIGHT, ~HEIGHTU, ~VSTESTCD, ~VSSTRESN, ~AAGECUR,
Don't know if you meant to separate the over/under by gender as well, but it would be nice to maybe do 1 each?

2024-06-30 21:51 UTC, ahasoplakus commented
> @ahasoplakus Thank you for all your help so far! Looks great, just needs a couple more examples, as cited above, is it possible to add outlier cases? Something like Z-scores of > |10| so both -10 and 10, with the currently pre-existing metadata, to make it easier you can generate fake data and use just one metadataset like the `who_wt_for_lgth_boys` to trim down the preprocessing work

Thanks @zdz2101 @Fanny-Gautier for your comments. Will add the outlier cases as suggested.

2024-07-04 08:00 UTC, rossfarrugia commented
@ahasoplakus might be worth using {covr} to check any lines in this function that are untested by your PR, as it could help find one or two more useful tests to add. i'm hoping to see after this PR and Laura's for the other function that we'll get our code coverage score up above 90%, as that's then in line with other admiral packages.

2024-07-04 09:32 UTC, ahasoplakus commented
> @ahasoplakus might be worth using {covr} to check any lines in this function that are untested by your PR, as it could help find one or two more useful tests to add. i'm hoping to see after this PR and Laura's for the other function that we'll get our code coverage score up above 90%, as that's then in line with other admiral packages.

@rossfarrugia I have ran `devtools::test_coverage_active_file()` which uses `file_coverage()` from {covr} and it seems all lines are covered
![image](https://github.com/pharmaverse/admiralpeds/assets/51382535/ced9066c-8c05-43b4-b227-0f281401baca)

2024-07-09 11:27 UTC, Fanny-Gautier approved these changes
No further comments

2024-07-09 12:19 UTC, rossfarrugia commented
Thanks @Fanny-Gautier! @zdz2101 please double check and approve if OK from your side.

2024-07-10 09:42 UTC, Fanny-Gautier commented on tests/testthat/test-derive_params_growth_height.R
> +    dataset = filter(vs_data, AAGECUR < 730),
Should the new argument `by_vars` be added there ?

2024-07-10 09:42 UTC, Fanny-Gautier commented on tests/testthat/test-derive_params_growth_height.R
> +    dataset = filter(vs_data, AAGECUR >= 730.5),
Should the new argument `by_vars` be added there ?

2024-07-10 09:42 UTC, Fanny-Gautier commented on tests/testthat/test-derive_params_growth_height.R
> +    dataset = vs_data,
Should the new argument `by_vars` be added there ?

2024-07-10 09:43 UTC, Fanny-Gautier commented on tests/testthat/test-derive_params_growth_height.R
> +      dataset = vs_data,
Should the new argument `by_vars` be added there ?

2024-07-11 19:55 UTC, zdz2101 approved these changes

2024-07-11 19:56 UTC, merged